// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practico2HDP.Data;

#nullable disable

namespace Practico2HDP.Migrations
{
    [DbContext(typeof(BiciContext))]
    [Migration("20230424015523_AgregoModelClientes")]
    partial class AgregoModelClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Practico2HDP.Models.Bicicleta", b =>
                {
                    b.Property<int>("BicicletaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsElectrica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TiendaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BicicletaID");

                    b.HasIndex("TiendaID");

                    b.ToTable("Bicicleta");
                });

            modelBuilder.Entity("Practico2HDP.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsumidorFinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Practico2HDP.Models.Tienda", b =>
                {
                    b.Property<int>("TiendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .HasColumnType("TEXT");

                    b.HasKey("TiendaID");

                    b.ToTable("Tienda");
                });

            modelBuilder.Entity("Practico2HDP.Models.Bicicleta", b =>
                {
                    b.HasOne("Practico2HDP.Models.Tienda", null)
                        .WithMany("Bicicletas")
                        .HasForeignKey("TiendaID");
                });

            modelBuilder.Entity("Practico2HDP.Models.Tienda", b =>
                {
                    b.Navigation("Bicicletas");
                });
#pragma warning restore 612, 618
        }
    }
}
